// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Headder: typeof import('./src/components/headder/index.vue')['default']
    NewStudent: typeof import('./src/components/newStudent/index.vue')['default']
    NutAddressList: typeof import('@nutui/nutui-taro')['AddressList']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutEmpty: typeof import('@nutui/nutui-taro')['Empty']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutNavbar: typeof import('@nutui/nutui-taro')['Navbar']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutTabbar: typeof import('@nutui/nutui-taro')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui-taro')['TabbarItem']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    NutToast: typeof import('@nutui/nutui-taro')['Toast']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
